ROLE_ADMIN = 1

DEVICE_STATUS_OFFLINE = 0
DEVICE_STATUS_ONLINE = 1

BACKUP_TYPE_FULL = 0
BACKUP_TYPE_SELECTED = 1
BACKUP_TYPE_AUTO = 2

BACKUP_STATUS_RUNNING = 0
BACKUP_STATUS_SUCCESS = 1
BACKUP_STATUS_FAILED = 2

JOB_STATUS_RUNNING = 0
JOB_STATUS_SUCCESS = 1
JOB_STATUS_FAILED = 2
JOB_STATUS_SKIPPED = 3
JOB_STATUS_PENDING = 4
